#!/usr/bin/env bash

LIBCLANG="/Library/Developer/CommandLineTools/usr/lib/libclang.dylib"
rm -fr bundle/ycm/ycm_build && mkdir bundle/ycm/ycm_build || exit   1
(cd bundle/ycm/ycm_build
cmake -DEXTERNAL_LIBCLANG_PATH="${LIBCLANG}" -G "Unix Makefiles" "../cpp" || exit 1
make -j$(sysctl -n hw.ncpu))
