#!/usr/bin/env bash

rm -fr "autoload" && mkdir "autoload" && curl -o "autoload/pathogen.vim" -L "https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
./update_plugins
./install_ycm
