#!/usr/bin/env bash

rm -fr "autoload" && mkdir "autoload" || exit 1
curl -Sso "autoload/pathogen.vim" \
    "https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim" || exit 1
git submodule update --init --recursive
$(pwd)/ycm_install
